const produtosOmie = [
  {
    combustivel: {},
    ide: {
      codigo_item: 2237980,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 70.2,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 70.2,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item:
        "INFORMACOES COMPLEMENTARES RESERVADO AO FISCO. PERMITE O APROVEITAMENTO DO CREDITO DE ICMS NO VALOR DE R$ 0,49. CORRESPONDENTE A ALIQUOTA DE 1,25, NOS TERMOS DO ART.23 DA LC 1232006.",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.023,
      peso_liquido: 0.004,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8901",
      codigo_produto: 2232167,
      codigo_tabela_preco: 0,
      descricao: "Colour - Batom 1 Pink Alva",
      ean: "4013640089010",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.10.00",
      percentual_desconto: 44.4444,
      quantidade: 1,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 31.2,
      valor_icms_desonerado: 0,
      valor_mercadoria: 70.2,
      valor_total: 39,
      valor_unitario: 70.2,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239207,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 140.4,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "0",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 140.4,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.023,
      peso_liquido: 0.004,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8902",
      codigo_produto: 2238291,
      codigo_tabela_preco: 0,
      descricao: "Coleur - BATOM 2 VINHO ALVA",
      ean: "4013640089027",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.10.00",
      percentual_desconto: 44.4444,
      quantidade: 2,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 62.4,
      valor_icms_desonerado: 0,
      valor_mercadoria: 140.4,
      valor_total: 78,
      valor_unitario: 70.2,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239221,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 70.2,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 70.2,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.023,
      peso_liquido: 0.004,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8906",
      codigo_produto: 2238329,
      codigo_tabela_preco: 0,
      descricao: "Coleur - BATOM C4 VINHO BRILHO ALVA",
      ean: "4013640089232",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.10.00",
      percentual_desconto: 44.4444,
      quantidade: 1,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 31.2,
      valor_icms_desonerado: 0,
      valor_mercadoria: 70.2,
      valor_total: 39,
      valor_unitario: 70.2,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239225,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 194.4,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 194.4,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.023,
      peso_liquido: 0.004,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8520",
      codigo_produto: 2238412,
      codigo_tabela_preco: 0,
      descricao: "Coleur - CORRETIVO 1  LIGHT ALVA",
      ean: "4013640085203",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.99.90",
      percentual_desconto: 44.4444,
      quantidade: 3,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 86.4,
      valor_icms_desonerado: 0,
      valor_mercadoria: 194.4,
      valor_total: 108,
      valor_unitario: 64.8,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239228,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 194.4,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 194.4,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.023,
      peso_liquido: 0.004,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8521",
      codigo_produto: 2238419,
      codigo_tabela_preco: 0,
      descricao: "Coleur - CORRETIVO 2 MÉDIO ALVA",
      ean: "4013640085210",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.99.90",
      percentual_desconto: 44.4444,
      quantidade: 3,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 86.4,
      valor_icms_desonerado: 0,
      valor_mercadoria: 194.4,
      valor_total: 108,
      valor_unitario: 64.8,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239235,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 99,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 99,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.091,
      peso_liquido: 0.009,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8560",
      codigo_produto: 2238461,
      codigo_tabela_preco: 0,
      descricao: "Coleur - PÓ BRONZEADOR 1 BEGE ROSÊ ALVA",
      ean: "4013640085401",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.91.00",
      percentual_desconto: 44.4444,
      quantidade: 1,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 44,
      valor_icms_desonerado: 0,
      valor_mercadoria: 99,
      valor_total: 55,
      valor_unitario: 99,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239238,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 99,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 99,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.091,
      peso_liquido: 0.009,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8561",
      codigo_produto: 2238470,
      codigo_tabela_preco: 0,
      descricao: "Coleur - PÓ BRONZEADOR 2 BEGE MÉDIO ALVA",
      ean: "4013640085418",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.91.00",
      percentual_desconto: 44.4444,
      quantidade: 1,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 44,
      valor_icms_desonerado: 0,
      valor_mercadoria: 99,
      valor_total: 55,
      valor_unitario: 99,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239247,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 99,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 99,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.091,
      peso_liquido: 0.009,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8562",
      codigo_produto: 2238479,
      codigo_tabela_preco: 0,
      descricao: "Coleur - PÓ BRONZEADOR 3 MARROM ALVA",
      ean: "4013640085609",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.91.00",
      percentual_desconto: 44.4444,
      quantidade: 1,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 44,
      valor_icms_desonerado: 0,
      valor_mercadoria: 99,
      valor_total: 55,
      valor_unitario: 99,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239253,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 82.8,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 82.8,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.091,
      peso_liquido: 0.009,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8540",
      codigo_produto: 2238489,
      codigo_tabela_preco: 0,
      descricao: "Coleur - PÓ COMPACTO 1 LIGHT ALVA",
      ean: "4013640085616",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.91.00",
      percentual_desconto: 44.4444,
      quantidade: 1,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 36.8,
      valor_icms_desonerado: 0,
      valor_mercadoria: 82.8,
      valor_total: 46,
      valor_unitario: 82.8,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239257,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 82.8,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 82.8,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.091,
      peso_liquido: 0.009,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8541",
      codigo_produto: 2238540,
      codigo_tabela_preco: 0,
      descricao: "Coleur - PÓ COMPACTO 2 MEDIUM ALVA",
      ean: "4013640085623",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.91.00",
      percentual_desconto: 44.4444,
      quantidade: 1,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 36.8,
      valor_icms_desonerado: 0,
      valor_mercadoria: 82.8,
      valor_total: 46,
      valor_unitario: 82.8,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239268,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 172.8,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 172.8,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.01,
      peso_liquido: 0,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8600",
      codigo_produto: 2238557,
      codigo_tabela_preco: 0,
      descricao: "Coleur - KAJAL 1 PRETO ALVA",
      ean: "4013640086002",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.20.90",
      percentual_desconto: 44.4444,
      quantidade: 3,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 76.8,
      valor_icms_desonerado: 0,
      valor_mercadoria: 172.8,
      valor_total: 96,
      valor_unitario: 57.6,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239271,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 172.8,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 172.8,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.01,
      peso_liquido: 0,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8601",
      codigo_produto: 2238584,
      codigo_tabela_preco: 0,
      descricao: "Coleur - KAJAL 2 MARROM BRILHANTE ALVA",
      ean: "4013640086019",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.20.90",
      percentual_desconto: 44.4444,
      quantidade: 3,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 76.8,
      valor_icms_desonerado: 0,
      valor_mercadoria: 172.8,
      valor_total: 96,
      valor_unitario: 57.6,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239275,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 57.6,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 57.6,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.01,
      peso_liquido: 0,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8680",
      codigo_produto: 2238661,
      codigo_tabela_preco: 0,
      descricao: "Coleur - DELINEADOR PARA OS LABIOS 1 ROSA TUMALINA",
      ean: "4013640086804",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.10.00",
      percentual_desconto: 44.4444,
      quantidade: 1,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 25.6,
      valor_icms_desonerado: 0,
      valor_mercadoria: 57.6,
      valor_total: 32,
      valor_unitario: 57.6,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239278,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 57.6,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 57.6,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.01,
      peso_liquido: 0,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "8681",
      codigo_produto: 2238670,
      codigo_tabela_preco: 0,
      descricao: "Coleur - DELINEADOR PARA OS LABIOS 2 VINHO TINTO",
      ean: "4013640086811",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.10.00",
      percentual_desconto: 44.4444,
      quantidade: 1,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 25.6,
      valor_icms_desonerado: 0,
      valor_mercadoria: 57.6,
      valor_total: 32,
      valor_unitario: 57.6,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239293,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 187.2,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 187.2,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.18,
      peso_liquido: 0.075,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "3107",
      codigo_produto: 2238805,
      codigo_tabela_preco: 0,
      descricao: "For Him - DESODORANTE SPRAY 75ml",
      ean: "4013640031071",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3307.20.10",
      percentual_desconto: 44.4444,
      quantidade: 4,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 83.2,
      valor_icms_desonerado: 0,
      valor_mercadoria: 187.2,
      valor_total: 104,
      valor_unitario: 46.8,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239313,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 86.4,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 86.4,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.03,
      peso_liquido: 0.004,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "7218",
      codigo_produto: 2238932,
      codigo_tabela_preco: 0,
      descricao: "Sanddorn - BÁLSAMO LABIAL SANDDORN 3,50 g",
      ean: "4013640072180",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.99.90",
      percentual_desconto: 44.4444,
      quantidade: 2,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 38.4,
      valor_icms_desonerado: 0,
      valor_mercadoria: 86.4,
      valor_total: 48,
      valor_unitario: 43.2,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239317,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 187.2,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 187.2,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.086,
      peso_liquido: 0.05,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "7202",
      codigo_produto: 2238962,
      codigo_tabela_preco: 0,
      descricao: "Sanddorn - CREME NUTRITIVO NOITE 50ml",
      ean: "4013640072029",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.99.90",
      percentual_desconto: 44.4444,
      quantidade: 2,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 83.2,
      valor_icms_desonerado: 0,
      valor_mercadoria: 187.2,
      valor_total: 104,
      valor_unitario: 93.6,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239320,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 151.2,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 151.2,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.049,
      peso_liquido: 0.015,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "7204",
      codigo_produto: 2238974,
      codigo_tabela_preco: 0,
      descricao: "Sanddorn - CREME PARA ÁREA DOS OLHOS 15ml",
      ean: "4013640072043",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.99.90",
      percentual_desconto: 44.4444,
      quantidade: 2,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 67.2,
      valor_icms_desonerado: 0,
      valor_mercadoria: 151.2,
      valor_total: 84,
      valor_unitario: 75.6,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239341,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 176.4,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 176.4,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.09,
      peso_liquido: 0.05,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "7201",
      codigo_produto: 2238994,
      codigo_tabela_preco: 0,
      descricao: "Sanddorn - CREME HIDRATANTE DIA 50ml",
      ean: "4013640072012",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.99.90",
      percentual_desconto: 44.4444,
      quantidade: 2,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 78.4,
      valor_icms_desonerado: 0,
      valor_mercadoria: 176.4,
      valor_total: 98,
      valor_unitario: 88.2,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239379,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 194.4,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 194.4,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.26,
      peso_liquido: 0.1,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "7213",
      codigo_produto: 2239025,
      codigo_tabela_preco: 0,
      descricao: "Sanddorn - ÓLEO PARA O CORPO SANDDORN 100ml",
      ean: "4013640072135",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.99.90",
      percentual_desconto: 44.4444,
      quantidade: 2,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 86.4,
      valor_icms_desonerado: 0,
      valor_mercadoria: 194.4,
      valor_total: 108,
      valor_unitario: 97.2,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239460,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 68.4,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 68.4,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.255,
      peso_liquido: 0.1,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "6752",
      codigo_produto: 2239412,
      codigo_tabela_preco: 0,
      descricao: "Rhassoul - TÔNICO FACIAL RHASSOUL 100 ml",
      ean: "4013640067520",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.99.90",
      percentual_desconto: 44.4444,
      quantidade: 1,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 30.4,
      valor_icms_desonerado: 0,
      valor_mercadoria: 68.4,
      valor_total: 38,
      valor_unitario: 68.4,
    },
    rastreabilidade: {},
    tributavel: {},
  },
  {
    combustivel: {},
    ide: {
      codigo_item: 2239473,
      codigo_item_integracao: "",
      simples_nacional: "N",
    },
    imposto: {
      cofins_padrao: {
        aliq_cofins: 0,
        base_cofins: 136.8,
        cod_sit_trib_cofins: "01",
        qtde_unid_trib_cofins: 0,
        tipo_calculo_cofins: "B",
        valor_cofins: 0,
        valor_unid_trib_cofins: 0,
      },
      cofins_st: {
        aliq_cofins_st: 0,
        base_cofins_st: 0,
        cod_sit_trib_cofins_st: "01",
        margem_cofins_st: 0,
        qtde_unid_trib_cofins_st: 0,
        tipo_calculo_cofins_st: "",
        valor_cofins_st: 0,
        valor_unid_trib_cofins_st: 0,
      },
      csll: {
        aliq_csll: 0,
        valor_csll: 0,
      },
      icms: {},
      icms_efet: {},
      icms_ie: {
        aliq_icms_FCP: 0,
        aliq_interestadual: 0,
        aliq_interna_uf_destino: 0,
        aliq_partilha_icms: 0,
        base_icms_uf_destino: 0,
        valor_fcp_icms_inter: 0,
        valor_icms_uf_dest: 0,
        valor_icms_uf_remet: 0,
      },
      icms_sn: {
        aliq_icms_sn: 0,
        base_icms_sn: 0,
        cod_sit_trib_icms_sn: "101",
        origem_icms_sn: "1",
        valor_credito_icms_sn: 0,
        valor_icms_sn: 0,
      },
      icms_st: {
        aliq_icms_opprop: 0,
        aliq_icms_st: 0,
        base_icms_st: 0,
        cest: "",
        cod_sit_trib_icms_st: "",
        margem_icms_st: 0,
        modalidade_icms_st: "",
        perc_red_base_icms_op: 0,
        perc_red_base_icms_st: 0,
        valor_icms_st: 0,
      },
      inss: {
        aliq_inss: 0,
        valor_inss: 0,
      },
      ipi: {
        aliq_ipi: 0,
        base_ipi: 0,
        cod_sit_trib_ipi: "53",
        enquadramento_ipi: "999",
        qtde_unid_trib_ipi: 0,
        tipo_calculo_ipi: "",
        valor_ipi: 0,
        valor_unid_trib_ipi: 0,
      },
      irrf: {
        aliq_irrf: 0,
        valor_irrf: 0,
      },
      iss: {
        aliq_iss: 0,
        base_iss: 0,
        retem_iss: "",
        valor_iss: 0,
      },
      pis_padrao: {
        aliq_pis: 0,
        base_pis: 136.8,
        cod_sit_trib_pis: "01",
        qtde_unid_trib_pis: 0,
        tipo_calculo_pis: "B",
        valor_pis: 0,
        valor_unid_trib_pis: 0,
      },
      pis_st: {
        aliq_pis_st: 0,
        base_pis_st: 0,
        cod_sit_trib_pis_st: "01",
        margem_pis_st: 0,
        qtde_unid_trib_pis_st: 0,
        tipo_calculo_pis_st: "",
        valor_pis_st: 0,
        valor_unid_trib_pis_st: 0,
      },
    },
    inf_adic: {
      codigo_categoria_item: "",
      codigo_local_estoque: 2141640863,
      dados_adicionais_item: "",
      item_pedido_compra: 0,
      nao_gerar_financeiro: "N",
      nao_movimentar_estoque: "N",
      numero_pedido_compra: "",
      peso_bruto: 0.253,
      peso_liquido: 0.125,
    },
    observacao: {},
    produto: {
      cfop: "5.102",
      cnpj_fabricante: "",
      codigo: "501007",
      codigo_produto: 2239471,
      codigo_tabela_preco: 0,
      descricao: "Óleo de Jojoba - ÓLEO DE JOJOBA 100% natural",
      ean: "4013640050102",
      indicador_escala: "",
      motivo_icms_desonerado: "",
      ncm: "3304.99.90",
      percentual_desconto: 44.4444,
      quantidade: 2,
      reservado: "N",
      tipo_desconto: "",
      unidade: "UN",
      valor_deducao: 0,
      valor_desconto: 60.8,
      valor_icms_desonerado: 0,
      valor_mercadoria: 136.8,
      valor_total: 76,
      valor_unitario: 68.4,
    },
    rastreabilidade: {},
    tributavel: {},
  },
];

const returnId = produtosOmie.map(({ produto }) => ({
  id: produto.codigo_produto,
}));

module.exports = { returnId };
